source 'http://rubygems.org'

gem 'sinatra'
gem 'dm-sqlite-adapter'
gem 'data_mapper'

# put in dev block
gem 'unicorn'
gem 'rspec'
gem 'rack-test'
gem 'ZenTest'
gem 'autotest-growl'
gem 'autotest-fsevent'
